title: Udemy Certificates
#logo: /assets/img/test.png
#description: test
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
